name: Abstractions

on:
  push:
    branches: [ main ]
    paths:
    - TestDatabase.Abstractions/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0
    - name: Install dependencies
      run: dotnet restore TestDatabase.Abstractions/TestDatabase.Abstractions.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore TestDatabase.Abstractions/TestDatabase.Abstractions.csproj
    - name: Pack
      run: dotnet pack --configuration Release --no-build --include-symbols --verbosity normal TestDatabase.Abstractions/TestDatabase.Abstractions.csproj
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: |
          ./TestDatabase.Abstractions/bin/Release/*.nupkg
    - name: Publish package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PACKAGE_NAME: TestDatabase.Abstractions
        PROJECT_FILE_PATH: ./TestDatabase.Abstractions/TestDatabase.Abstractions.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
